# Generated by Django 4.1.1 on 2023-08-23 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeTracerApp', '0002_cryptocurrencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrencies',
            name='circulatingSuply',
        ),
        migrations.RemoveField(
            model_name='cryptocurrencies',
            name='marketCap',
        ),
        migrations.RemoveField(
            model_name='cryptocurrencies',
            name='symbol',
        ),
    ]
